
import AsyncStorage from '@react-native-async-storage/async-storage';

export const defaultPetProfiles = [
    {
        id: 1,
        type: 'Dogs',
        breed: 'German Shepherd',
        // name: 'Rocky',
        image: require('./assets/dog1.png'),
        temperament: 'Loyal',
        training: 'Advanced Obedience Trained',
        vaccinated: 'Yes',
        description: 'Rocky is a loyal German Shepherd with advanced obedience training. He is known for his intelligence and makes a great companion. Rocky is vaccinated and ready for a loving home.',
        address: '📌 German Shepherd Haven',
        gender: '♂️ M',
        age: '⏳2',
        isAdopted: false,
        isVerified: 1,
    },

    {
        id: 2,
        type: 'Cats',
        breed: 'Cristen Reynoso',
        temperament: 'Elegant',
        training: 'Graceful Movements',
        // name: 'Luna',
        vaccinated: 'Yes',
        description: 'Luna, the elegant Cristen Reynoso cat, is known for her graceful movements and charming personality. She is vaccinated and looking for a home where she can showcase her regal charm.',
        image: require('./assets/cat1.png'),
        address: '📌 Reynoso Feline Palace',
        gender: '♀️ F',
        age: '⏳2',
        isAdopted: false,
        isVerified: 1,
    },
    {
        id: 3,
        type: 'Others',
        breed: 'Parrot',
        temperament: 'Chatty',
        training: 'Speech Trained',
        // name: 'Polly',
        vaccinated: 'Yes',
        description: 'Meet Polly, the chatty parrot with a vibrant personality. Polly is speech trained and loves interacting with people. Adopt Polly for a feathered friend.',
        image: require('./assets/bird2.png'),
        address: '📌 Tropical Aviaries',
        gender: '♀️ F',
        age: '⏳3',
        isAdopted: false,
        isVerified: 1,
    },

    {
        id: 4,
        type: 'Dogs',
        breed: 'Labrador Retriever',
        // name: 'Max',
        image: require('./assets/dog2.png'),
        temperament: 'Energetic',
        training: 'Advanced Training in Progress',
        vaccinated: 'No',
        description: 'Max, the Labrador Retriever, is full of energy and undergoing advanced training. Max is looking for an active family who can provide the love and care he deserves.',
        address: '📌 Happy Tails Shelter',
        gender: '♀️ F',
        age: '⏳1',
        isAdopted: false,
        isVerified: 1,
    },

    {
        id: 5,
        type: 'Cats',
        breed: 'Maine Coon',
        // name: 'Fluffy',
        image: require('./assets/cat3.png'),
        temperament: 'Gentle',
        training: 'Basic Training Completed',
        vaccinated: 'Yes',
        description: 'Fluffy, the gentle Maine Coon, has completed basic training and is ready for adoption. Fluffy loves cozying up and enjoys a calm environment.',
        address: '📌 Whisker Wonderland',
        gender: '♂️ M',
        age: '⏳3',
        isAdopted: false,
        isVerified: 1,
    },

    {
        id: 6,
        type: 'Others',
        breed: 'Dwarf Rabbit',
        temperament: 'Playful',
        training: 'Litter Training in Progress',
        // name: 'Cotton',
        vaccinated: 'No',
        description: 'Cotton, the playful dwarf rabbit, is currently undergoing litter training. Cotton is looking for a caring family who can provide a safe and fun environment.',
        image: require('./assets/bunny2.png'),
        address: '📌 Bunny Haven',
        gender: '♀️ F',
        age: '⏳2',
        isAdopted: false,
        isVerified: 1,
    },
    {
        id: 7,
        type: 'Others',
        breed: 'new data',
        temperament: 'Playful',
        training: 'Litter Training in Progress',
        // name: 'Cotton',
        vaccinated: 'No',
        description: 'Cotton, the playful dwarf rabbit, is currently undergoing litter training. Cotton is looking for a caring family who can provide a safe and fun environment.',
        image: require('./assets/bunny2.png'),
        address: '📌 Bunny Haven',
        gender: '♀️ F',
        age: '⏳2',
        isAdopted: false,
        isVerified: 1,
      },
      {
        id: 8,
        type: 'Others',
        breed: 'abc',
        temperament: 'Playful',
        training: 'Litter Training in Progress',
        // name: 'Cotton',
        vaccinated: 'No',
        description: 'Cotton, the playful dwarf rabbit, is currently undergoing litter training. Cotton is looking for a caring family who can provide a safe and fun environment.',
        image: require('./assets/bird1.png'),
        address: '📌 Bunny Haven',
        gender: '♀️ F',
        age: '⏳2',
        isAdopted: false,        
        isVerified: 1,
      },
];
